env:
  browser: true
  worker: true

extends:
  - airbnb
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint

plugins:
  - react-hooks

rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/order:
    - error
    - newlines-between: never
  react/jsx-curly-newline: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - jsx
        - tsx
  react/no-array-index-key: warn
  react/prop-types: off
  react-hooks/rules-of-hooks: error
